import { ArrowRight, Boxes, Layers3, ShieldCheck, Store } from "lucide-react";
import Link from "next/link";

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[#f7f6ff] dark:bg-zinc-950">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Link href="/" className="flex items-center gap-2 text-lg font-bold"><span className="grid size-9 place-items-center rounded-xl bg-violet-600 text-white">N</span>Nexo Commerce</Link><div className="flex items-center gap-2"><Link href="/login" className="rounded-xl px-4 py-2 text-sm font-semibold hover:bg-white dark:hover:bg-zinc-900">Ingresar</Link><Link href="/register" className="rounded-xl bg-zinc-900 px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-zinc-900">Crear cuenta</Link></div></header>
    <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-20 lg:grid-cols-2 lg:py-28"><div className="absolute -right-40 top-0 -z-0 size-[500px] rounded-full bg-violet-300/30 blur-3xl" /><div className="relative z-10"><p className="mb-5 inline-flex rounded-full border border-violet-200 bg-white/70 px-3 py-1 text-sm font-semibold text-violet-700 dark:border-violet-900 dark:bg-violet-950/50 dark:text-violet-300">E-commerce modular · 100% local</p><h1 className="max-w-2xl text-5xl font-bold leading-[1.05] tracking-[-.05em] sm:text-7xl">Una base sólida para todas tus tiendas.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-zinc-600 dark:text-zinc-400">Creá, aislá y administrá múltiples comercios con usuarios y permisos reales. Sin servicios pagos ni dependencias externas obligatorias.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register" className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 font-semibold text-white shadow-lg shadow-violet-600/20">Crear mi primera tienda <ArrowRight className="size-4" /></Link><Link href="/login" className="rounded-xl border border-zinc-200 bg-white px-5 py-3 font-semibold dark:border-zinc-700 dark:bg-zinc-900">Ver demo local</Link></div></div>
      <div className="relative z-10 rounded-[2rem] border border-white/80 bg-white/75 p-4 shadow-2xl shadow-violet-900/10 backdrop-blur dark:border-zinc-800 dark:bg-zinc-900/80"><div className="rounded-2xl bg-zinc-950 p-5 text-white"><div className="mb-10 flex items-center justify-between"><span className="font-semibold">Panel multitienda</span><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs text-emerald-300">Sistema activo</span></div><div className="grid grid-cols-2 gap-3">{[[Store, "Tiendas", "2"], [ShieldCheck, "Roles", "5"], [Layers3, "Aislamiento", "storeId"], [Boxes, "Arquitectura", "modular"]].map(([Icon, label, value]) => { const C = Icon as typeof Store; return <div key={String(label)} className="rounded-2xl bg-white/7 p-4"><C className="mb-6 size-5 text-violet-300" /><p className="text-xs text-zinc-400">{String(label)}</p><p className="mt-1 text-xl font-bold">{String(value)}</p></div>; })}</div></div></div>
    </section>
  </main>;
}
